### ISSUE TITLE
[Icon Request] PDF Icon

### ISSUE THREAD

**Issue by phoerious** [chadalen/vscode-jetbrains-icon-theme#32]
I'm using VS Code for LaTeX editing and would like a PDF file icon.

(An icon for .tex files would be great as well)

**Comment by chadalen** [comment]
For .tex files we can use icon from [here](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/resources/nl/hannahsten/texifyidea/icons/latex-file.svg)
![latex-file](https://user-images.githubusercontent.com/12568665/165798151-f278afcc-a420-4488-9b2c-da3aeb514c59.svg)


For .pdf files we can use icon from [here](https://github.com/Hannah-Sten/TeXiFy-IDEA/blob/master/resources/nl/hannahsten/texifyidea/icons/pdf-file.svg)
![pdf-file](https://user-images.githubusercontent.com/12568665/165798555-e6f7a280-54f5-44f0-9867-9b57f401b459.svg)

**Comment by phoerious** [comment]
I created a few icons myself, what do you think?

![bbl min](https://user-images.githubusercontent.com/911270/165835644-cc43c684-f155-495a-a004-0cf6ed7dde51.svg)
![pdf min](https://user-images.githubusercontent.com/911270/165835646-ccbafa68-b221-42e2-9b20-d3054205045a.svg)
![tex min](https://user-images.githubusercontent.com/911270/165835648-32a35c63-0129-4e64-a972-0e09e083798b.svg)
![aux min](https://user-images.githubusercontent.com/911270/165835651-8cb4e76a-1db7-41a4-8622-0aa7c4213188.svg)

**Comment by chadalen** [comment]
> I created a few icons myself, what do you think? I couldn't find out what exactly the font used in the original icons is, but this is the closest match I could find on Adobe Fonts. The characters are all pixel-aligned.

Hey nice job, this is great. 🙂

So this is what your icons will look like.
<img width="127" alt="Screen Shot 2022-04-29 at 12 27 48 AM" src="https://user-images.githubusercontent.com/12568665/165885907-7d0a9386-ff64-482e-b6d1-40284febdb16.png">

The only thing I notice is the "E" in the TEX icon is touching the border at the bottom so it looks kinda goofy in my option. What do you think about that? Is that how you want it? It may look better if you raise the text by a pixel. Let me know what you think but we can definitely use these new icons you made.

**Comment by phoerious** [comment]
If I raise it, it touches to top border, which is worse I would say. I think that's fine. But I may actually lighten up the Acrobat red a bit. Will do that in the evening.

**Comment by chadalen** [comment]
> If I raise it, it touches the top border, which is worse I would say. I think that's fine. But I may actually lighten up the Acrobat red a bit. Will do that in the evening.

What about having TEX all on one line so it's more consistent with the rest of the icons? In my option that would look cleaner and more readable.

I'll let you design them though. Once you approve the look of the icons I'll go ahead and merge the [PR](https://github.com/chadalen/vscode-jetbrains-icon-theme/pull/33) I have open for this.

**Comment by phoerious** [comment]
I think the TeX icon is fine like that and more recognizable. I'll make two more for sty und cls tomorrow and then we can merge it.

**Comment by chadalen** [comment]
> Shall we keep the original .ai files somewhere? They could also serve as templates for other icons.

We could store the .ai files here in git although I don't see any other vscode icon theme repo doing that. I'm closing this ticket these changes have been merged in see [PR](https://github.com/chadalen/vscode-jetbrains-icon-theme/pull/33). These changes will be in the 1.0.12 release which I'm deploying right now.
